### PR TITLE
Show ROS users that the sdk can be build using catkin

### PR DESCRIPTION
**Pull request by Timple**
After https://github.com/QuanergySystems/quanergy_client/pull/24

This PR is optional, the previous method still works.

### CODE REVIEW

**Comment by worldpotato** [comment]
That works? I need to test it! Thanks for showing me!

**Comment by rossctaylor** [comment]
This needs to be updated for merge to devel because of switch from 16.04 support to 20.04 support.

**Comment by Timple** [comment]
Done

**Comment by Timple** [comment]
Rebased

**Comment by rossctaylor** [comment]
Thanks @Timple

**Comment by rossctaylor** [comment]
Actually, @Timple I think catkin_make_isolated is required instead of catkin_make because of the non-ros library. I'll double check and fix that but let me know if you don't think that is right. catkin build would also work but would require different installation instructions.

**Comment by Timple** [comment]
Good point, we use `catkin build` indeed.

I believe catkin_tools is also recommended these days, so maybe convert the instructions to that?

**Comment by rossctaylor** [comment]
Fixed with catkin_make_isolated for now.

**Pull request merged**
